### ISSUE TITLE
Milestone 2 Minimum Requirements

### ISSUE THREAD

**Issue by cole-rogers** [iHell/poe-it#1]
- [X] Set up a MySQL database 
-  [x] Set all of your tables (from [Milestone 1](https://www.cs.virginia.edu/~up3f/cs4750/project/index.html#!/pm1)) in your MySQL database
- [x] Populate the database with your chosen dataset. The data should be realistic and sufficient to demonstrate that your project is practical 
- [X] Write at least two of the following advanced SQL commands to efficiently manage the business logic of your app
